{{- if eq .Values.tenancyEngine "kiosk" -}}
{{- if eq .Values.global.platform "kubernetes" -}}
{{- if .Values.manageNamespace -}}
apiVersion: config.kiosk.sh/v1alpha1
kind: Account
metadata:
  labels:
    {{- include "cd-pipeline-operator.labels" . | nindent 4 }}
  name: {{ .Release.Namespace }}
spec:
  space:
    clusterRole: kiosk-space-admin
  subjects:
    - kind: ServiceAccount
      name: edp-{{ .Values.name }}
      namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
{{- end -}}
