{{- if eq .Values.global.platform "kubernetes" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edp-{{ .Values.name }}-{{ .Values.global.edpName }}-kiosk-edit
subjects:
  - kind: ServiceAccount
    name: edp-{{ .Values.name }}
    namespace: {{ .Values.global.edpName }}
roleRef:
  kind: ClusterRole
  name: kiosk-edit
  apiGroup: rbac.authorization.k8s.io
{{- end -}}