apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cdpipelines.v2.edp.epam.com
spec:
  group: v2.edp.epam.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                inputDockerStreams:
                  type: array
                  items:
                    type: string
                applicationsToPromote:
                  nullable: true
                  type: array
                  items:
                    type: string
                deploymentType:
                  type: string
              required:
                - name
                - deploymentType
            status:
              additionalProperties: true
              type: object
      subresources:
        status: {}
  conversion:
    strategy: None
  scope: Namespaced
  names:
    kind: CDPipeline
    listKind: CDPipelineList
    plural: cdpipelines
    singular: cdpipeline
    shortNames:
      - cdp