global:
  # -- namespace or a project name (in case of OpenShift)
  edpName: ""
  # -- platform type that can be "kubernetes" or "openshift"
  platform: "kubernetes"

# -- component name
name: cd-pipeline-operator

# -- defines the type of the tenant engine that can be "none", "kiosk" or "capsule"
tenancyEngine: "none"

annotations: {}
nodeSelector: {}
tolerations: []
affinity:
image:
  # -- EDP cd-pipeline-operator Docker image name. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/cd-pipeline-operator)
  repository: epamedp/cd-pipeline-operator
  # if not defined then .Chart.AppVersion is used
  # -- EDP cd-pipeline-operator Docker image tag. The released image can be found on [Dockerhub](https://hub.docker.com/r/epamedp/cd-pipeline-operator/tags)
  tag:
imagePullPolicy: "IfNotPresent"

resources:
  limits:
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

# -- should the operator manage(create/delete) namespaces for stages
manageNamespace: true

# -- manageSecrets is a flag that indicates whether the operator should manage secrets for stages
manageSecrets: false
